### ISSUE TITLE
lftp-mirror-action uploads all files every time it runs despite setting "onlyNewer: true"

### ISSUE THREAD

**Issue by ghost** [pressidium/lftp-mirror-action#5]
Hi everyone,

I read the section https://github.com/pressidium/lftp-mirror-action#restoring-modification-times, but I'm not sure I understand it correctly. Since I still encounter the issue that all my files are being uploaded every time, even after adding "onlyNewer: true". I'm also not sure if I need to add "fetch-depth: 0" and if this is connected to the issue. It added it and still same issue with uploading all files instead of only newer files.

Please see my ```main.yaml``` below. Do you have any suggstions what I am missing?

```
on: push
name: Publish to IONOS
jobs:
  web-deploy:
    name: HN MVP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        # lftp settings
        onlyNewer: true
        # Mirror command options
        localDir: '.'
        remoteDir: './HN'
        reverse: true
```

Thank you in advance!

**Comment by over-engineer** [comment]
Hey, @HyveNow!

>I'm also not sure if I need to add "fetch-depth: 0"

Yes, setting `fetch-depth` to `0` is required in order to fetch the entire Git history, and restore the modification time of the files based on the date of the most recent commit that modified them (as described in the [Restoring modification times](https://github.com/pressidium/lftp-mirror-action#restoring-modification-times) section that you mentioned).

The GitHub Actions workflow you provided (assuming `fetch-depth` was also set to `0`) seems to be correct.

```yaml
- name: Get latest code
  uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

>same issue with uploading all files instead of only newer files.

I just ran it on another GitHub repository with that configuration and I couldn’t reproduce the issue (only modified files with a newer timestamp were transferred), so there’s probably something else we’re missing :thinking:

Is this the entire `main.yaml`? Are there any additional steps in the `web-deploy` job, or any other jobs defined in the workflow?

**Comment by ghost** [comment]
Hey @over-engineer , thank for the quick reply! 

Yes, that is the entire `main.yaml`. Now added back the `fetch-depth: 0`. Please see below.

Any command I should try to run? Like [git-restore-mtime-action](https://github.com/chetan/git-restore-mtime-action) ? Did not fully understand if this would help.

`main.yaml`:
```
on: push
name: Publish to IONOS
jobs:
  web-deploy:
    name: HN MVP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Sync files
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        # lftp settings
        onlyNewer: true
        # Mirror command options
        localDir: '.'
        remoteDir: './HN'
        reverse: true
```

Thanks and best!
