### ISSUE TITLE
`.lftp_ignore` file - Location and syntax - Excluding directories/files

### ISSUE THREAD

**Issue by cnoss** [pressidium/lftp-mirror-action#6]
… first: thanks for the action! 

Where do I have to put the `.lftp_ignore` File and how should the syntax inside looks like?

**Comment by over-engineer** [comment]
Hey, @cnoss!

>Where do I have to put the `.lftp_ignore` File

By default, `lftp-mirror-action` looks for the `.lftp_ignore` file at the root of your GitHub repository.

You can adjust that by setting the `ignoreFile` input to specify a different filename/path, like this:

```yaml
[...]
- name: Deploy files via SFTP
  uses: pressidium/lftp-mirror-action@v1
  with:
    [...]
    ignoreFile: 'my_custom_ignore_file'
```

>how should the syntax inside looks like?

Each line in the `.lftp_ignore` file specifies a pattern for directories/files to exclude.

Comments (i.e. lines starting with `#`) and blank lines are disregarded.

For example, if you’d like to exclude the `.git/` and `.github/` directories, and the `.gitignore` and `README.md` files, you could enter the following in your `.lftp_ignore` file:

```
# Directories to exclude
.git/
.github/

# Files to exclude
.gitignore
README.md
```

Please note that, unlike `.gitignore`, you **cannot** use the `!` prefix to negate a pattern.
