### ISSUE TITLE
Deploy action is not deleting files renamed or removed from the repository.

### ISSUE THREAD

**Issue by JangoBritt** [pressidium/lftp-mirror-action#7]
I renamed a file from `birch_tree_feature.json` to `birch_tree_feature.bak`, and while it successfully uploaded the new `.bak` file, it did not remove the old `.json` file.

How do I configure the deployment to recognize removed files?

**Comment by over-engineer** [comment]
Hey, @JangoBritt!

>How do I configure the deployment to recognize removed files?

Setting the `delete` option will automatically delete any files not present at the source.

You need to add:

```yaml
options: 'delete'
```

to your GitHub Actions workflow, like this:

```yaml
- name: Deploy
  uses: pressidium/lftp-mirror-action@v1
  with:
    host: ${{ secrets.SFTP_HOST }}
    port: ${{ secrets.SFTP_PORT }}
    user: ${{ secrets.SFTP_USER }}
    pass: ${{ secrets.SFTP_PASS }}
    remoteDir: '/var/www/html/example.com/public'
    options: 'delete'
```

I hope that helps—let me know if that works for you!

**Comment by JangoBritt** [comment]
Thanks! 

I assume that takes into account .gitignore(d) files?

**Comment by over-engineer** [comment]
>I assume that takes into account .gitignore(d) files?

By default, `.lftp_ignore` is used as the ignore list in `pressidium/lftp-mirror-action`, though you can override this by specifying the `ignoreFile` parameter.

For example,

```yaml
- name: Deploy
  uses: pressidium/lftp-mirror-action@v1
  with:
    host: ${{ secrets.SFTP_HOST }}
    port: ${{ secrets.SFTP_PORT }}
    user: ${{ secrets.SFTP_USER }}
    pass: ${{ secrets.SFTP_PASS }}
    ignoreFile: '.lftp_ignore'
    options: 'delete'
```

Suppose your Git repository includes the following contents:

```
├── .github
│   └── workflows
│       └── deploy.yml
├── .gitignore
├── .lftp_ignore
├── bar.txt
├── buzz.txt
└── foo.txt
```

Here’s an an example of what the `.lftp_ignore` file might include:

```
## Directories to exclude
.git/
.github/

## Files to exclude
.gitignore
.lftp_ignore
README.md
foo.txt
```

Running the GitHub Actions workflow will upload these files to the remote server:

* `bar.txt`
* `buzz.txt`

The `foo.txt` file won’t be transferred since it’s ignored.

On the remote server, the directory will look like this:

```
├── bar.txt
└── buzz.txt
```

Here’s what would happen if you:

1. Create a `foo.txt` file on your remote server
2. Delete the `foo.txt` file from your Git repository
2. Delete the `bar.txt` file from your Git repository

As a result, the source (Git repository) now looks like this:

```
├── .github
│   └── workflows
│       └── deploy.yml
├── .gitignore
├── .lftp_ignore
└── buzz.txt
```

Meanwhile, the target (remote server) contains:

```
├── bar.txt
├── buzz.txt
└── foo.txt
```

Re-running the GitHub Actions workflow will delete `bar.txt` from the remote server, while leaving `foo.txt` intact.

So, the final state of the remote server will be:

```
├── buzz.txt
└── foo.txt
```

Please let me know if you have any further questions!
