### ISSUE TITLE
Workflow stuck at Sync-Files process

### ISSUE THREAD

**Issue by opmat** [pressidium/lftp-mirror-action#8]
I recently deploy SFTP Github action using this module and the action is stuck for over 3 hours now on Sync-Files process. What cn be the issue and what am I doing wrong?

**WHAT I'VE DONE**
My Github Action yml file content is below

```
name: SFTP Deploy to Test Server 

on:
  push:
    branches:
      - dev

jobs:
  web-deploy:

    name: Deploy

    runs-on: ubuntu-latest

    steps:
    -   name: Get latest Code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

    -   name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    -   name: Install dependencies in root directory
        uses: php-actions/composer@v6
        with:
            working_dir: ""
            php_version: "8.3" 
            php_extensions: zip intl xmlrpc
            args: "--ignore-platform-reqs --optimize-autoloader"

    -   name: Install dependencies in slim api directory
        uses: php-actions/composer@v6
        env:
            COMPOSER: "composer.json"
        with:
            working_dir: "apyv1"
            php_version: "8.3"
            php_extensions: zip intl xmlrpc
            args: "--ignore-platform-reqs --optimize-autoloader"

    -   name: Sync-Files
        uses: pressidium/lftp-mirror-action@v1
            #SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
            # SFTP credentials
            host: ${{ secrets.KKON_DEMO_FTP_HOST }}
            port: 22
            user: ${{ secrets.KKON_DEMO_FTP_USER }}
            pass: ${{ secrets.KKON_DEMO_FTP_PASS }}
            # lftp settings
            onlyNewer: true
            settings: 'sftp:auto-confirm=yes'
            # Mirror command options
            # localDir: '.'
            remoteDir: '/home/directoryyHome/pubicDir/'
            reverse: true

```

The process won't complete as in the attached image. Any help will be appreciated

<img width="1053" alt="Image" src="https://github.com/user-attachments/assets/3b80419e-a4c5-4cc8-a5e1-fa0f13042a79" />

**Comment by linkion** [comment]
It is still probably running, I'd put the --verbose flag to log the individual file transfers with:

```yml
- name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.FTP_HOST }}
          port: 22
          user: ${{ secrets.FTP_USER }}
          pass: ${{ secrets.FTP_PASSWORD }}
          parallel: 10
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          remoteDir: '/public_html/'
          reverse: true
          options: '--verbose'
```
